# Generated by Django 2.1.5 on 2019-04-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slider_val',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
